repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      exclude: misc
      additional_dependencies: [
        'flake8-builtins==1.4.2',
        'flake8-bugbear==20.1.4',
        'flake8-comprehensions==3.2.2',
      ]
      language_version: python3.8
-   repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        args:
          - "-lll"
-   repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: helmlint
