repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
-   repo: https://github.com/ambv/black
    rev: 23.10.1
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      exclude: misc
      additional_dependencies: [
        'flake8-builtins==2.1.0',
        'flake8-bugbear==23.7.10',
        'flake8-comprehensions==3.14.0',
      ]
      language_version: python3.8
-   repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args:
          - "-lll"
-   repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22
    hooks:
      - id: helmlint
