FROM python:3.8-slim

RUN apt-get update && apt-get install -y git && rm -rf /var/cache/apt/*

WORKDIR /app

COPY requirements.txt /app/requirements.txt
COPY requirements-dev.txt /app/requirements-dev.txt

RUN pip3 install -r requirements-dev.txt
RUN git config --global init.defaultBranch master

ENV PYTHONPATH=/app
